#ifndef LOCATIONLIST_H
#define LOCATIONLIST_H

typedef enum
{
    LOCATION_TYPE_INVALID,
    LOCATION_TYPE_CHEST,
    LOCATION_TYPE_CUTSCENE,
    LOCATION_TYPE_SONG,
    LOCATION_TYPE_NPC,
    LOCATION_TYPE_COLLECTABLE,
    LOCATION_TYPE_EVENT,
    LOCATION_TYPE_CHEST,
    LOCATION_TYPE_BOSS,
    LOCATION_TYPE_BOSS_HEART,
    LOCATION_TYPE_GS_TOKEN,
    LOCATION_TYPE_SHOP,
    LOCATION_TYPE_GROTTONPC,
    LOCATION_TYPE_GOSSIPSTONE
} location_type_e;

typedef enum
{
    LOCATION_HINT_NONE,
    LOCATION_HINT_KOKIRI_FOREST,
    LOCATION_HINT_THE_GRAVEYARD,
    LOCATION_HINT_DEATH_MOUNTAIN_TRAIL,
    LOCATION_HINT_GORON_CITY,
    LOCATION_HINT_ZORAS_DOMAIN,
    LOCATION_HINT_GERUDO_VALLEY,
    LOCATION_HINT_GERUDOS_FORTRESS,
    LOCATION_HINT_HAUNTED_WASTELAND,
    LOCATION_HINT_KAKARIKO_VILLAGE,
    LOCATION_HINT_SACRED_FOREST_MEADOW,
    LOCATION_HINT_DESERT_COLOSSUS,
    LOCATION_HINT_HYRULE_FIELD,
    LOCATION_HINT_ZORAS_RIVER,
    LOCATION_HINT_THE_LOST_WOODS,
    LOCATION_HINT_DEATH_MOUNTAIN_CRATER,
    LOCATION_HINT_THE_MARKET,
    LOCATION_HINT_TEMPLE_OF_TIME,
    LOCATION_HINT_ZORAS_FOUNTAIN,
    LOCATION_HINT_HYRULE_CASTLE,
    LOCATION_HINT_OUTSIDE_GANONS_CASTLE,
    LOCATION_HINT_ICE_CAVERN,
    LOCATION_HINT_LON_LON_RANCH,
    LOCATION_HINT_LAKE_HYLIA,
    LOCATION_HINT_BOTTOM_OF_THE_WELL,
    LOCATION_HINT_SPIRIT_TEMPLE,
    LOCATION_HINT_GANONS_CASTLE,
    LOCATION_HINT_DEKU_TREE,
    LOCATION_HINT_DODONGOS_CAVERN,
    LOCATION_HINT_JABU_JABUS_BELLY,
    LOCATION_HINT_FOREST_TEMPLE,
    LOCATION_HINT_FIRE_TEMPLE,
    LOCATION_HINT_WATER_TEMPLE,
    LOCATION_HINT_SHADOW_TEMPLE,
    LOCATION_HINT_GERUDO_TRAINING_GROUNDS,
    LOCATION_HINT_LINKS_POCKET,
} location_hint_e;

#endif // !LOCATIONLIST_H
