#ifndef WORLD_H
#define WORLD_H


#define TRIALS_FOREST 0
#define TRIALS_FIRE 1
#define TRIALS_WATER 2
#define TRIALS_SPIRIT 3
#define TRIALS_SHADOW 4
#define TRIALS_LIGHT 5


#define DUNGEON_DEKU_TREE 0
#define DUNGEON_DODONGOS_CAVERN 1
#define DUNGEON_JABU_JABUS_BELLY 2
#define DUNGEON_FOREST_TEMPLE 3
#define DUNGEON_FIRE_TEMPLE 4
#define DUNGEON_WATER_TEMPLE 5
#define DUNGEON_SPIRIT_TEMPLE 6
#define DUNGEON_SHADOW_TEMPLE 7
#define DUNGEON_BOTTOM_OF_THE_WELL 8
#define DUNGEON_ICE_CAVERN 9
#define DUNGEON_GANONS_TOWER 10
#define DUNGEON_GERUDO_TRAINING_GROUNDS 11
#define DUNGEON_THIEVES_HIDEOUT 12
#define DUNGEON_GANONS_CASTLE 13

#endif